var rule = {
  title: '',
  host: 'http://cechi7.com/',
  编码:'gb2312',
  搜索编码:'gb2312',
  url: '/fyclass/indexfypage.html[/fyclass/index.html]',
  searchUrl: '/search.asp?searchword=**',
  searchable: 0,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  class_name:'电视剧&电影&短剧&综艺&香港剧&韩国剧&欧美剧&喜剧片&科幻片&恐怖片&剧情片&战争片&动画片',
   class_url:'dianshiju/guochanju&dianying/dongzuopian&dianshiju/duanju&zongyiyule/daluzongyi&dianshiju/hongkongju&dianshiju/hanguoju&dianshiju/oumeiju&dianying/xijupian&dianying/kehuanpian&dianying/kongbupian&dianying/juqingpian&dianying/zhanzhengpian&dianying/dhdy',
  play_parse: true,
 lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  //cate_exclude:'国产剧|午夜剧场|wuyejuchang|xiezhen|伦理片|写真',
  推荐: 'ul.myui-vodlist.clearfix;li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
  double: true,
  一级: '.myui-vodlist li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
  tab_order:['百度影音','lzm3u8'],
  二级: {
    title: '.myui-content__detail .title&&Text;.myui-content__detail p.data&&Text',
    img: '.myui-content__thumb .lazyload&&data-original',
    desc: '.myui-content__detail p:eq(0)&&Text;.myui-content__detail p:eq(1)&&Text;.myui-content__detail p:eq(2)&&Text',
    content: '.myui-content__detail p:eq(6)&&Text',
    tabs: '.nav-tabs:eq(0) li',
    lists: '.myui-content__list:eq(#id) li',
  },
  搜索: 'body #searchList li:not(:matches(伦理片|写真|主播|vip));a&&title;.lazyload&&data-original;.text-muted&&Text;a&&href;.text-muted:eq(2)&&Text',
}
