var rule = {
  title: '',
  host: 'http://97dt.com/',
  编码:'gb2312',
  搜索编码:'gb2312',
  url: '/fyclass/indexfypage.html[/fyclass/index.html]',
  searchUrl: '/search.asp?searchword=**',
  searchable: 0,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6788.76 Safari/537.36',
  },
  class_name:'电视剧&电影&短剧&综艺&香港剧&韩国剧&欧美剧&喜剧片&科幻片&恐怖片&剧情片&战争片&动画片',
   class_url:'dianshiju/guochanju&dianying/dongzuopian&dianshiju/duanju&zongyiyule/daluzongyi&dianshiju/hongkongju&dianshiju/hanguoju&dianshiju/oumeiju&dianying/xijupian&dianying/kehuanpian&dianying/kongbupian&dianying/juqingpian&dianying/zhanzhengpian&dianying/dhdy',
  play_parse: true,
 lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  //cate_exclude:'国产剧|午夜剧场|wuyejuchang|xiezhen|伦理片|写真',
  double: true,
  一级: '.list_tab_img li;a&&title;img&&data-original;.name&&Text;a&&href',
  //tab_order:['百度影音','lzm3u8'],
  二级: {
    title: '.vod-n-l h1&&Text;.vod-n-l p:eq(3)&&Text',
    img: '.vod-n-img img&&src',
    desc: '.vod-n-l p:eq(1)&&Text;.vod-n-l p:eq(0)&&Text;.vod-n-l p:eq(5)&&Text;.vod-n-l p:eq(4)&&Text;.vod-n-l p:eq(2)&&Text',
    content: '.v-js.clear.yc&&Text',
    tabs: '.play-title span:eq(1) a',
    lists: '.plau-ul-list:eq(#id) a',
  },
  搜索: '.up-tb .list_tab_img li:not(:matches(伦理片|写真|主播|vip));a&&title;img&&data-original;.name&&Text;a&&href',
}