var rule = {
  title: '',
  host: 'http://wenhi.com/',
  url: '/fyclass/indexfypage.html[/fyclass/index.html]',
  searchUrl: '/search.php?page=fypage&searchword=**&searchtype=',
  searchable: 0,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'Mozilla/5.0 (Linux; Android 13; SM-A536E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36 uacq',
  },
   class_parse: 'ul.type-slide.clearfix li;a&&Text;a&&href;.*/(.*?)/index.html',
  //class_name:'电影&电视剧&动漫&综艺',
   //class_url:'dianying/dongzuopian&dianshiju/guochanju&3&4',
  play_parse: true,
  lazy: '',
  limit: 6,
  //cate_exclude:'国产剧|午夜剧场|wuyejuchang|xiezhen|伦理片|写真',
  推荐: 'ul.stui-vodlist.clearfix;li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
  double: true,
  一级: '.stui-vodlist.clearfix li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.stui-content__detail p:eq(3)&&a:eq(0)&&Text',
    img: '.stui-content__thumb .lazyload&&data-original',
    desc: '.stui-content__detail p:eq(0)&&Text;.stui-content__detail p:eq(3)&&a:eq(3)&&Text;.stui-content__detail p:eq(3)&&a:eq(2)&&Text',
    content: '.stui-content__detail p:eq()&&span:eq(1)&&Text',
    tabs: '.stui-pannel__head.bottom-line:eq(0) h3',
    lists: '.stui-pannel-box .stui-content__playlist.playlink.clearfix:eq(#id) li',
  },
  搜索: '.stui-vodlist__media.col-pd.clearfix li;a&&title;.lazyload&&data-original;.pic-text.text-right&&Text;a&&href',
}