var rule = {
  title: '西瓜',
  host: 'https://www.a6club.com/',
  url: '/index.php/vod/show/id/fyclass/page/fypage.html',
  searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.61 Chrome/126.0.6478.61 Not/A)Brand/8 Safari/537.36',
  },
  class_parse: '.border-shadow&&.movie-list-header;.movie-list-title&&Text;a&&href;.*/(.*?).html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  double: true,
  推荐: '.movie-list-body.flex;.movie-list-item;.movie-title.txtHide&&Text;.Lazy.br&&data-original;.movie-rating.cor4&&Text;a&&href',
  一级: '.movie-list-body&&.movie-list-item;.movie-title.txtHide&&Text;.Lazy.br&&data-original;.movie-rating.cor4&&Text;a&&href',
  二级: {
    title: 'h1.movie-title&&Text;.fed-deta-content&&.fed-part-rows&&li&&Text',
    img: '.poster&&img&&src',
    desc: '.fed-deta-content&&.fed-part-rows&&li:eq(1)&&Text;.fed-deta-content&&.fed-part-rows&&li:eq(2)&&Text;.fed-deta-content&&.fed-part-rows&&li:eq(3)&&Text',
    content: '.summary.detailsTxt&&Text',
    tabs: '#tag&&a',
    tab_text: '.titleName&&Text',
    lists: '.content_playlist.flex.wrap:eq(#id) li',
  },
  搜索: '.vod-search-list;.txtHide&&Text;.Lazy.br&&data-original;.cor4&&Text;a&&href;.fed-deta-content&&Text',
}