var rule = {
  title: 'jin',
  host: 'https://api.zeqaht.com/',
  homeTid: '14',
  homeUrl: '/api.php/provide/vod/?ac=detail&t={{rule.homeTid}}',
  detailUrl: 'https://www.cfkj86.com/detail/fyid',
  searchUrl: '/api.php/provide/vod/?wd=**&pg=fypage',
  url: '/api.php/provide/vod/?ac=detail&pg=fypage&t=fyclass',
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
  },
  timeout: 5000,
  class_parse: 'json:class;',
  limit: 20,
  multi: 1,
  searchable: 2,
  quickSearch: 1,
  filterable: 0,
  play_parse: true,
  parse_url: '',
  lazy: "js:\n        let url_id = input.split('/')[5];\n        let jishu_id = input.split('/')[7];\n        let t = new Date().getTime();\n        eval(getCryptoJS);\n        let signkey = 'id=' + url_id + '&nid=' + jishu_id + '&key=cb808529bae6b6be45ecfab29a4889bc&t=' + t;\n        let key = CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\n        let json_data = JSON.parse(request('https://www.cfkj86.com/api/mw-movie/anonymous/video/episode/url?id=' + url_id + '&nid=' + jishu_id, {\n            headers: {\n                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',\n                'deviceid': '58a80c52-138c-48fd-8edb-138fd74d12c8',\n                'sign': key,\n                't': t\n            }\n        }));\n        let url = json_data.data;\n        log(url);\n        if (url) {\n            input = {parse: 0, url: url, header: rule.headers};\n        }\n\n    ",
  推荐: '*',
  一级: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_play_from',
 二级: {
      title: 'h1&&Text',
      img: 'img&&src',
    tabs: '.main-list-sections__HeadArea-sc-8bb7334b-1 .player_name',
    tab_text: 'body&&Text',
    lists: '.kZjMVJ:eq(#id) a',
    list_text: 'a&&Text',
    list_url: 'a&&href',
    },
  搜索: '*',
}
