var rule = {
     title: '文才2[资]',
    host: 'https://api.zeqaht.com',
    homeTid: '75',
    homeUrl: 'https://api.zeqaht.com/api.php/provide/vod/?ac=detail&t=75',
    detailUrl: 'https://www.gs4x7nq4.com/detail/fyid',
    searchUrl: 'https://api.zeqaht.com/index.php/ajax/suggest?mid=1&wd=**&limit=100',
    url: 'https://api.zeqaht.com/index.php/ajax/data?mid=1&tid=fyfilter&page=fypage&limit=20',
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
      'Referer': 'https://www.gs4x7nq4.com/',
      'Origin': 'https://www.gs4x7nq4.com/',
      'Connection': 'keep-alive',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
      'Cookie': '__51vcke__3I14AJXLSVMADZTk=43308954-257c-5b39-85fd-844b128507fc; __51vuft__3I14AJXLSVMADZTk=1717815879622; __vtins__3I14AJXLSVMADZTk=%7B%22sid%22%3A%20%228cceb4d1-e1eb-5d1c-a9d0-e280f8f3fc2c%22%2C%20%22vd%22%3A%201%2C%20%22stt%22%3A%200%2C%20%22dr%22%3A%200%2C%20%22expires%22%3A%201734579480032%2C%20%22ct%22%3A%201734577680032%7D; __51uvsct__3I14AJXLSVMADZTk=8',
      'Service-Worker-Navigation-Preload': 'true',
    },
    timeout: 5000,
    class_parse: '',
    limit: 20,
    multi: 1,
    searchable: 2,
    quickSearch: 1,
    filterable: 0,
    play_parse: true,
    parse_url: '',
    lazy: "js:\n      let url_id = input.split('/')[5];\n      let jishu_id = input.split('/')[7];\n      let t = new Date().getTime();\n      eval(getCryptoJS);\n      let signkey = 'id=' + url_id + '&nid=' + jishu_id + '&key=b34b0e013cbd149e7662a2bdcca434a01069334e&t=' + t;\n      let key = CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\n      let json_data = JSON.parse(request('https://www.gs4x7nq4.com/api/mw-movie/anonymous/video/episode/url?id=' + url_id + '&nid=' + jishu_id, {\n         headers: {\n            'User-Agent': PC_UA,\n            'deviceid': '98766db1-1058-4d76-8fc8-49b1137af7ca',\n            'sign': key,\n            't': t\n         }\n      }));\n      let url = json_data.data;\n      log(url);\n      if (url) {\n         input = {\n            parse: 0,\n            url: url,\n            header: rule.headers\n         };\n      }\n\n   ",
    推荐: '*',
    一级: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_play_from',
    二级: {
      title: '.title&&Text;',
      img: '',
      desc: ';;;;',
      content: '.wrapper_more_text&&Text',
      tabs: '.player_name',
      lists: '.listitem a',
    },
    搜索: 'json:list;name;pic;;id',
    模板: '采集1',
    filter_url: '{{fl.分类}}',
    filter: 'H4sIAAAAAAAAA7WSwU6DQBCG7z4F2TOHFihUX8V46IGT2psmpmliS6jAQa0xqLWJpwaqTWovRqHt08CuvIWFVIbZ7rWEA/D9uzvfMJ0DaXuROjmSjjsSOTWvNk8kdQZsERNZIu3WuVl8cQNq2fmXy9bZhbmNtwtkh5kVFih/JVJXlkrmjzcrS6YomHphshoDVRFlwTD9iUuq1jB1Fv8FFWt1RGl/xvwhUAOfO7mp7tzkKKgW52JKe/f02geKz2XenK3egTZ4X/ZYMcK+1PJofwRUw9R5TiIXjLidBw/ZyxTW1nFVvXU2WoMvpqn9lcRgpOVVnWxuGcZD2dd4vK6SKKhOSJ2zngVsfYsCWJx+z9O7TxTgJuFpkr1NqwFdEeijQHO3A+peO8Di5a8bQQGHAkcuY9QEmnxGETSTz6iCbvAZbbch2n5Hwgvp8gMKaIj+KZfRRZPDZYytSOHR/QP/scWLAQUAAA==',
    filter_def: {
      '1': {
        分类: '1',
      },
      '2': {
        分类: '2',
      },
      '3': {
        分类: '3',
      },
      '4': {
        分类: '4',
      },
    },
    图片替换: 'https://api.zeqaht.com=>https://obs.gduamoe.com',
    class_name: '电影&电视&综艺&动漫',
    class_url: '1&2&3&4',
    cate_exclude: '首页|留言|APP|下载|资讯|新闻|动态',
    tab_exclude: '猜你|喜欢|下载|剧情|榜|评论',
    类型: '影视',
    double: false,
    二级访问前: '',
    encoding: 'utf-8',
    search_encoding: '',
    图片来源: '',
    play_json: [],
    pagecount: {},
    proxy_rule: '',
    sniffer: false,
    isVideo: '',
    tab_remove: [],
    tab_order: [],
    tab_rename: {},
  }
