var rule = {
  title: '',
  host: 'https://jczy.jinchan.pro/',
  homeTid: '2',
  homeUrl: '/api.php/provide/vod/?ac=detail&t={{rule.homeTid}}',
  detailUrl: '/api.php/provide/vod/?ac=detail&ids=fyid',
  searchUrl: '/api.php/provide/vod/?wd=**&pg=fypage',
  url: '/api.php/provide/vod/?ac=detail&pg=fypage&t=fyclass',
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  class_name:'电视剧&电影&综艺&动漫',
  tab_remove:'失效',
   class_url:'2&1&3&4',
  limit: 20,
  multi: 1,
  searchable: 2,
  quickSearch: 1,
  filterable: 0,
  play_parse: true,
  parse_url: '',
  lazy:'js:input="https://openapi.973973.xyz/open/api_free/index?pltfrom=5010&url="+input.split("?")[0];log(input);let html=JSON.parse(request(input));log(html);input=html.url||input',
  推荐: '*',
  一级: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_play_from',
  二级: 'js:\n            let html=request(input);\n            html=JSON.parse(html);\n            let data=html.list;\n            VOD=data[0];',
  搜索: '*',
}
